### ISSUE TITLE
Make this an official client

### ISSUE THREAD

**Issue by psiinon** [SUSE/owasp_zap#1]
Would you like this to be an 'official' client?
You'll need to commit the generator to the ZAP repo, but you can maintain this as a separate project.
In any case I've linked to this project from: https://code.google.com/p/zaproxy/wiki/ApiDetails

Many thanks, 

Simon (ZAP Project lead)

**Comment by vpereira** [comment]
Hi @psiinon , great to hear from you! With a generator you mean, like the api generator for the python api? I was thinking about it, but before I would like to get it in good shape. Maybe in the version 1.0? 

<3 ZAP!

**Comment by psiinon** [comment]
Yeah, just like that :)
Just let me know when you're happy with it and we can 'officialize' it!

**Comment by ebadiere** [comment]
Is anyone watching this repo?  I can make use of this gem.

**Comment by vpereira** [comment]
hi, yes you can :)

**Comment by vpereira** [comment]
closed
