### ISSUE TITLE
Controlling maximum depth to crawl using ruby gem owasp_zap

### ISSUE THREAD

**Issue by ambikashri** [SUSE/owasp_zap#5]
Hello,
I wanted to know if we could control the depth to crawl in spidering using owasp_zap gem in ruby or could we pass parameters while calling the spider

```
spider = zap.spider
```

Also can we limit the number of urls visted during active scan in ruby?

**Comment by vpereira** [comment]
it was already fixed on vpereira/owasp_zap

**Comment by vpereira** [comment]
already fixed
